/**
 * End-to-End тест Platform API — проходит весь путь клиента-курьерки.
 *
 * Запуск:
 *   node server/scripts/test_platform_e2e.js
 *
 * Опции через env:
 *   API_BASE  — базовый URL (по умолчанию http://localhost:3001/api/platform)
 *   API_KEY   — ключ (если не задан, создаётся новый через сидер)
 *   TEST_IIN  — ИИН для тестов (по умолчанию проверочный)
 *
 * Что тестирует:
 *   1) GET  /             — описание API (без ключа)
 *   2) GET  /me           — проверка ключа
 *   3) POST /iin/validate — валидация ИИН
 *   4) GET  /iin/validate/:iin — то же через GET
 *   5) GET  /taxpayer/:bin — поиск налогоплательщика
 *   6) GET  /income-limit/status/:iin — статус лимита
 *   7) GET  /income-limit/check — предварительная проверка
 *   8) POST /income-limit/record — запись выплаты
 *   9) POST /process-payment — МАГИЯ: всё в одном
 *  10) Сценарий: 6 выплат по 250к ₸ → должно сработать BLOCK на 7-й
 */

// Опциональный dotenv — если установлен
try { require('dotenv').config({ path: __dirname + '/../.env' }); } catch {}
const http = require('http');
const https = require('https');
const { URL } = require('url');

const API_BASE = process.env.API_BASE || 'http://localhost:3001/api/platform';
const API_KEY  = process.env.API_KEY  || null;
// Известные ВАЛИДНЫЕ тестовые ИИН (сгенерированы алгоритмически):
//   850101100012 — 1985-01-01, мужской, XX век
//   900515200011 — 1990-05-15, женский, XX век
const TEST_IIN = process.env.TEST_IIN || '850101100012';

// ── HTTP helper ─────────────────────────────────────────────────────────────
function request(method, path, body, headers = {}) {
  return new Promise((resolve, reject) => {
    const url = new URL(path.startsWith('http') ? path : API_BASE + path);
    const isHttps = url.protocol === 'https:';
    const lib = isHttps ? https : http;

    const options = {
      method,
      hostname: url.hostname,
      port: url.port || (isHttps ? 443 : 80),
      path: url.pathname + url.search,
      headers: {
        'Content-Type': 'application/json',
        ...headers,
      },
    };

    const req = lib.request(options, (res) => {
      let buf = '';
      res.on('data', (c) => (buf += c));
      res.on('end', () => {
        let parsed;
        try { parsed = JSON.parse(buf); } catch { parsed = buf; }
        resolve({ status: res.statusCode, body: parsed });
      });
    });
    req.on('error', reject);
    if (body) req.write(JSON.stringify(body));
    req.end();
  });
}

// ── Цвета в консоли ─────────────────────────────────────────────────────────
const c = {
  green:  (s) => `\x1b[32m${s}\x1b[0m`,
  red:    (s) => `\x1b[31m${s}\x1b[0m`,
  yellow: (s) => `\x1b[33m${s}\x1b[0m`,
  cyan:   (s) => `\x1b[36m${s}\x1b[0m`,
  bold:   (s) => `\x1b[1m${s}\x1b[0m`,
};

let passed = 0;
let failed = 0;

function check(name, ok, details = '') {
  if (ok) {
    console.log(c.green('  ✅  ') + name);
    passed++;
  } else {
    console.log(c.red('  ❌  ') + name);
    if (details) console.log('      ' + c.red(details));
    failed++;
  }
}

function section(title) {
  console.log('\n' + c.bold(c.cyan('━━ ' + title + ' ━━')));
}

// ── Тесты ───────────────────────────────────────────────────────────────────
async function main() {
  console.log(c.bold('\n╔══════════════════════════════════════════════════════════════════╗'));
  console.log(c.bold('║  E2E ТЕСТ PLATFORM API — путь курьерской службы                 ║'));
  console.log(c.bold('╚══════════════════════════════════════════════════════════════════╝'));
  console.log(`\nAPI_BASE: ${API_BASE}`);
  console.log(`TEST_IIN: ${TEST_IIN}`);

  let apiKey = API_KEY;

  // ── 0. Создаём ключ (если не задан) ───────────────────────────────────────
  if (!apiKey) {
    section('0. Создание demo API-ключа');
    try {
      const crypto = require('crypto');
      const db = require('../src/db');
      const { migratePlatform } = require('../src/services/platform_db');
      await migratePlatform();

      apiKey = 'test_e2e_' + crypto.randomBytes(12).toString('hex');
      const ALL_FEATURES = [
        'iin_validate', 'taxpayer_info', 'income_limit', 'process_payment',
        'fiscalize', 'cancel_receipt', 'receipt_status',
        'self_employed_registry', 'benefits',
      ];
      await db.query(
        `INSERT INTO platform_api_keys
           (api_key, client_name, tier, features, monthly_quota, notes)
         VALUES ($1, 'E2E Test Client', 'enterprise', $2::jsonb, 10000, 'auto-generated by test_platform_e2e.js')`,
        [apiKey, JSON.stringify(ALL_FEATURES)],
      );
      console.log('  ✅  Ключ создан: ' + apiKey);
    } catch (err) {
      console.log('  ❌  Не смог создать ключ: ' + err.message);
      console.log('     Передай API_KEY через env, либо запусти сервер с подключённой БД');
      process.exit(1);
    }
  }

  const H = { 'X-Platform-Key': apiKey };

  // ── 1. Описание API ───────────────────────────────────────────────────────
  section('1. GET / — описание API (открытый)');
  const r1 = await request('GET', '/').catch((e) => ({ error: e.message }));
  check('Сервер отвечает', r1.status === 200, r1.error || `status ${r1.status}`);
  check('Возвращает список сервисов', Array.isArray(r1.body?.services));
  check('9 сервисов в списке', r1.body?.services?.length >= 8);

  // ── 2. /me ────────────────────────────────────────────────────────────────
  section('2. GET /me — проверка ключа');
  const r2 = await request('GET', '/me', null, H);
  check('Ключ принят (200)', r2.status === 200, JSON.stringify(r2.body));
  check('Возвращает имя клиента', !!r2.body?.client);
  check('Возвращает список фич', Array.isArray(r2.body?.features));

  // Проверка с НЕВАЛИДНЫМ ключом
  const r2bad = await request('GET', '/me', null, { 'X-Platform-Key': 'wrong_key_xxx' });
  check('Невалидный ключ → 403', r2bad.status === 403);

  // ── 3. POST /iin/validate ─────────────────────────────────────────────────
  section('3. POST /iin/validate — валидация ИИН (алгоритм)');
  const r3 = await request('POST', '/iin/validate', { iin: TEST_IIN }, H);
  check('Endpoint отвечает', r3.status === 200);
  check('Поле "valid" есть', 'valid' in (r3.body || {}));
  console.log('      Результат для ' + TEST_IIN + ': ' + (r3.body?.valid ? c.green('valid') : c.yellow('invalid: ' + r3.body?.reason)));

  // Заведомо некорректный ИИН
  const r3bad = await request('POST', '/iin/validate', { iin: '999999999999' }, H);
  check('Некорректный ИИН → valid=false', r3bad.body?.valid === false);

  // Слишком короткий
  const r3short = await request('POST', '/iin/validate', { iin: '123' }, H);
  check('Короткий ИИН → valid=false', r3short.body?.valid === false);

  // ── 4. GET /iin/validate/:iin ─────────────────────────────────────────────
  section('4. GET /iin/validate/:iin — тот же тест через GET');
  const r4 = await request('GET', `/iin/validate/${TEST_IIN}`, null, H);
  check('GET-вариант работает', r4.status === 200);
  check('Возвращает то же поле "valid"', 'valid' in (r4.body || {}));

  // ── 5. GET /taxpayer/:bin ─────────────────────────────────────────────────
  section('5. GET /taxpayer/:bin — поиск налогоплательщика (stat.gov.kz)');
  const r5 = await request('GET', `/taxpayer/${TEST_IIN}`, null, H);
  if (r5.status === 200) {
    check('Endpoint отвечает (200)', true);
    if (r5.body?.found_in_registry) {
      check('Найден в реестре stat.gov.kz', true);
      console.log('      Имя: ' + (r5.body?.name || '?'));
      console.log('      ОКЭД: ' + (r5.body?.oked?.main_code || '?') + ' — ' + (r5.body?.oked?.main_name || '?'));
    } else {
      console.log(c.yellow('  ⚠  ИИН не найден в реестре stat.gov.kz (возможно, ИП ещё не зарегистрирован)'));
    }
  } else if (r5.status === 502) {
    console.log(c.yellow('  ⚠  stat.gov.kz недоступен (403/блок IP) — fallback на структуру БИН сработал'));
    check('Fallback отвечает (502 с warning)', true);
  } else {
    check('Endpoint должен был ответить', false, `status ${r5.status}`);
  }

  // ── 6. /income-limit/status ───────────────────────────────────────────────
  section('6. GET /income-limit/status/:iin — текущий лимит');
  const r6 = await request('GET', `/income-limit/status/${TEST_IIN}`, null, H);
  check('Endpoint отвечает', r6.status === 200);
  check('Лимит = 1 297 500 ₸ (300 МРП × 4 325)', r6.body?.limit?.tenge === 1297500);
  check('Поле "used_tenge" есть', 'used_tenge' in (r6.body || {}));
  console.log('      Использовано: ' + (r6.body?.used_tenge || 0) + ' ₸');
  console.log('      Осталось: ' + (r6.body?.remaining_tenge || 0) + ' ₸');

  // ── 7. /income-limit/check ────────────────────────────────────────────────
  section('7. GET /income-limit/check — предварительная проверка');
  const r7 = await request('GET',
    `/income-limit/check?iin=${TEST_IIN}&proposed_amount=50000`,
    null, H);
  check('Endpoint отвечает', r7.status === 200);
  check('Поле "can_pay" есть', 'can_pay' in (r7.body || {}));

  // ── 8. POST /income-limit/record ──────────────────────────────────────────
  section('8. POST /income-limit/record — записать выплату');
  const r8 = await request('POST', '/income-limit/record', {
    iin: TEST_IIN,
    amount: 10000,
    external_id: `e2e_test_${Date.now()}`,
    payment_method: 'card',
    note: 'E2E test record',
  }, H);
  check('Endpoint отвечает (201)', r8.status === 201);
  check('Запись создана', r8.body?.recorded === true);

  // ── 9. /process-payment — МАГИЯ ───────────────────────────────────────────
  section('9. POST /process-payment — единый endpoint для курьерки');
  const r9 = await request('POST', '/process-payment', {
    courier_iin: TEST_IIN,
    amount: 30000,
    order_id: `e2e_order_${Date.now()}`,
    payment_method: 'card',
  }, H);
  check('Endpoint отвечает', r9.status === 200 || r9.status === 409);
  check('Возвращает поле "decision"', 'decision' in (r9.body || {}));
  console.log('      Decision: ' + c.bold(r9.body?.decision));
  console.log('      ИИН валиден: ' + r9.body?.iin_valid);
  console.log('      Фискальный статус: ' + r9.body?.fiscal_status);
  console.log('      Обработано за: ' + r9.body?.processed_in_ms + ' мс');

  // ── 10. Сценарий: исчерпание лимита ───────────────────────────────────────
  section('10. Сценарий BLOCK — 6 выплат по 250 000 ₸ должны исчерпать лимит');
  const stressIin = '900515200011'; // валидный: 1990-05-15, женский, XX век
  // Идемпотентность: чистим данные stress-IIN от прошлых прогонов теста,
  // иначе накопленные выплаты сразу дадут BLOCK на 1-й операции.
  try {
    const db = require('../src/db');
    await db.query(
      'DELETE FROM platform_self_employed_income WHERE iin = $1', [stressIin]);
    await db.query(
      'DELETE FROM platform_receipts WHERE iin = $1', [stressIin]);
  } catch (e) {
    console.log(c.yellow('  ⚠  Не смог очистить stress-IIN: ' + e.message));
  }
  // Сначала проверим валидность тестового ИИН
  const stressCheck = await request('POST', '/iin/validate', { iin: stressIin }, H);
  if (stressCheck.body?.valid !== true) {
    console.log(c.yellow('  ⚠  Stress-тест ИИН не валиден, пропускаем сценарий 10'));
  } else {
    let blockedAt = null;
    for (let i = 1; i <= 7; i++) {
      const r = await request('POST', '/process-payment', {
        courier_iin: stressIin,
        amount: 250000,
        order_id: `stress_${Date.now()}_${i}`,
        skip_taxpayer_check: true,
      }, H);
      console.log(`      Выплата ${i}: ${r.body?.decision} (${r.body?.income_limit?.would_be_total} / 1 297 500 ₸)`);
      if (r.body?.decision === 'BLOCK') {
        blockedAt = i;
        break;
      }
    }
    check('Лимит сработал на 6-й или 7-й выплате', blockedAt === 6 || blockedAt === 7,
      `blocked at #${blockedAt}`);
  }

  // ── 11. GET /receipts/:order_id — статус конкретного чека ─────────────────
  section('11. GET /receipts/:order_id — статус чека');
  // Создаём заказ, потом запрашиваем его статус
  const receiptOrderId = `e2e_receipt_${Date.now()}`;
  await request('POST', '/process-payment', {
    courier_iin: TEST_IIN,
    amount: 12000,
    order_id: receiptOrderId,
    skip_taxpayer_check: true,
  }, H);
  const r11 = await request('GET', `/receipts/${receiptOrderId}`, null, H);
  check('Endpoint отвечает (200)', r11.status === 200, `status ${r11.status}`);
  check('order_id совпадает', r11.body?.order_id === receiptOrderId);
  check('Есть поле status', 'status' in (r11.body || {}));
  check('Есть человекочитаемый status_label', !!r11.body?.status_label);
  check('Есть флаг is_fiscalized', 'is_fiscalized' in (r11.body || {}));
  console.log('      Статус: ' + (r11.body?.status || '?'));

  // Несуществующий чек → 404
  const r11bad = await request('GET', '/receipts/NONEXISTENT_ORDER_XYZ', null, H);
  check('Несуществующий чек → 404', r11bad.status === 404);

  // ── 12. GET /receipts — список чеков ─────────────────────────────────────
  section('12. GET /receipts — список чеков клиента');
  const r12 = await request('GET', '/receipts?limit=10', null, H);
  check('Endpoint отвечает (200)', r12.status === 200, `status ${r12.status}`);
  check('Есть поле total', 'total' in (r12.body || {}));
  check('Есть массив receipts', Array.isArray(r12.body?.receipts));
  check('Есть summary по статусам', typeof r12.body?.summary === 'object');
  console.log('      Всего чеков у клиента: ' + (r12.body?.total ?? '?'));
  // Фильтр по статусу
  const r12f = await request('GET', '/receipts?status=cancelled&limit=5', null, H);
  check('Фильтр по статусу работает', r12f.status === 200 &&
    Array.isArray(r12f.body?.receipts) &&
    r12f.body.receipts.every((x) => x.status === 'cancelled'));

  // ── Итог ──────────────────────────────────────────────────────────────────
  console.log('\n' + c.bold('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'));
  console.log(c.bold(`  ИТОГ:  ${c.green(passed + ' прошли')}, ${failed > 0 ? c.red(failed + ' упали') : c.green('0 упали')}`));
  console.log(c.bold('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'));
  console.log('\nAPI-ключ для дальнейшего тестирования:\n  ' + apiKey + '\n');

  process.exit(failed > 0 ? 1 : 0);
}

main().catch((err) => {
  console.error(c.red('\n❌ Тест упал с ошибкой:'), err);
  process.exit(1);
});
